/* ==========================================================================
   Constants & Strings
   ========================================================================== */

export const STRINGS = {
  errorRequired: "Dieses Feld ist erforderlich.",
  errorFutureDate: "Das Datum darf nicht in der Zukunft liegen.",
  errorPositiveNumber: "Bitte geben Sie einen Wert größer 0 ein.",
  errorEppoCode: "Bitte wählen Sie einen gültigen EPPO-Code aus der Liste aus.",
  errorBbchCode: "Bitte wählen Sie ein gültiges BBCH-Stadium aus der Liste aus.",
  errorLocationFormat: "Bitte geben Sie gültige Koordinaten (z. B. 48.2082, 16.3738) oder eine FLIK-Nummer ein.",
  errorNoResults: "Keine Ergebnisse. Bitte prüfen Sie die Schreibweise oder geben Sie den Code manuell ein.",
  errorEppoLoad: "EPPO-Code-Daten konnten nicht geladen werden. Die Suche ist nicht verfügbar.",
  errorBbchLoad: "BBCH-Daten konnten nicht geladen werden. Die Suche ist nicht verfügbar.",
  errorPsmLoad: "PSM-Register konnte nicht geladen werden. Produktnamen und Zulassungsnummern müssen manuell eingegeben werden.",
  errorJsPdfLoad: "PDF-Bibliothek konnte nicht geladen werden. Bitte stellen Sie eine Internetverbindung her und laden Sie die Seite neu.",
  gpsPermissionDenied: "Standortzugriff wurde verweigert. Bitte versuchen Sie einen anderen Browser (z. B. Firefox) oder geben Sie die Koordinaten manuell ein.",
  gpsUnavailable: "Standort konnte nicht ermittelt werden. Bitte prüfen Sie Ihre GPS-Verbindung oder geben Sie die Koordinaten manuell ein.",
  gpsTimeout: "Standortermittlung hat zu lange gedauert. Bitte versuchen Sie es erneut oder geben Sie die Koordinaten manuell ein.",
  gpsLoading: "Standort wird ermittelt...",
  gpsSuccess: "Standort erfolgreich ermittelt.",
  pdfDisclaimer: "Dieser Nachweis wurde mit OpenPSM erstellt. Die inhaltliche Richtigkeit und Vollständigkeit obliegt dem Anwender.",
  productRemove: "Produkt entfernen",
};

export const MAX_SUGGESTIONS = 10;
export const DEBOUNCE_MS = 150;
export const MAX_PRODUCT_ROWS = 10;
export const FORM_CACHE_KEY = "openpsm-form-cache";

export const CULTURE_TO_BBCH_GROUP = {
  "getreide": "Getreide",
  "weizen": "Getreide",
  "gerste": "Getreide",
  "roggen": "Getreide",
  "hafer": "Getreide",
  "triticale": "Getreide",
  "dinkel": "Getreide",
  "spelz": "Getreide",
  "einkorn": "Getreide",
  "emmer": "Getreide",
  "reis": "Reis",
  "mais": "Mais",
  "raps": "Raps",
  "rübsen": "Raps",
  "senf": "Raps",
  "ölrübsen": "Raps",
  "faba-bohne": "Faba-Bohne",
  "ackerbohne": "Faba-Bohne",
  "puffbohne": "Faba-Bohne",
  "sonnenblume": "Sonnenblume",
  "zuckerrübe": "Beta-Rüben",
  "futterrübe": "Beta-Rüben",
  "rote rübe": "Beta-Rüben",
  "rote beete": "Beta-Rüben",
  "kartoffel": "Kartoffel",
  "apfel": "Kernobst",
  "birne": "Kernobst",
  "quitte": "Kernobst",
  "kirsche": "Steinobst",
  "süßkirsche": "Steinobst",
  "sauerkirsche": "Steinobst",
  "pflaume": "Steinobst",
  "zwetschge": "Steinobst",
  "pfirsich": "Steinobst",
  "nektarine": "Steinobst",
  "aprikose": "Steinobst",
  "mandel": "Steinobst",
  "johannisbeere": "Johannisbeere",
  "stachelbeere": "Johannisbeere",
  "beerenobst": "Johannisbeere",
  "erdbeere": "Erdbeere",
  "zitrone": "Citrus",
  "orange": "Citrus",
  "mandarine": "Citrus",
  "grapefruit": "Citrus",
  "olive": "Olive",
  "kaffee": "Kaffee",
  "banane": "Bananenpflanzen",
  "wein": "Weinrebe",
  "weinrebe": "Weinrebe",
  "soja": "Sojabohne",
  "sojabohne": "Sojabohne",
  "baumwolle": "Baumwolle",
  "erdnuss": "Erdnuss",
  "hopfen": "Hopfen",
  "zwiebel": "Zwiebelgemüse",
  "knoblauch": "Zwiebelgemüse",
  "lauch": "Zwiebelgemüse",
  "schnittlauch": "Zwiebelgemüse",
  "karotte": "Wurzel- und Knollengemüse",
  "möhre": "Wurzel- und Knollengemüse",
  "rettich": "Wurzel- und Knollengemüse",
  "sellerie": "Wurzel- und Knollengemüse",
  "pastinake": "Wurzel- und Knollengemüse",
  "kopfsalat": "Blattgemüse (kopfbildend)",
  "endivie": "Blattgemüse (kopfbildend)",
  "chicorée": "Blattgemüse (kopfbildend)",
  "radicchio": "Blattgemüse (kopfbildend)",
  "spinat": "Blattgemüse (nichtkopfbildend)",
  "mangold": "Blattgemüse (nichtkopfbildend)",
  "kohl": "Sonstige Kohlgemüsearten",
  "brokkoli": "Sonstige Kohlgemüsearten",
  "blumenkohl": "Sonstige Kohlgemüsearten",
  "chinakohl": "Sonstige Kohlgemüsearten",
  "rotkohl": "Sonstige Kohlgemüsearten",
  "weißkohl": "Sonstige Kohlgemüsearten",
  "gurke": "Gurkengewächse",
  "melone": "Gurkengewächse",
  "kürbis": "Gurkengewächse",
  "zucchini": "Gurkengewächse",
  "tomate": "Nachtschattengewächse",
  "aubergine": "Nachtschattengewächse",
  "paprika": "Nachtschattengewächse",
  "chili": "Nachtschattengewächse",
  "erbse": "Erbse",
  "bohne": "Bohne",
  "buschbohne": "Bohne",
  "stangenbohne": "Bohne",
  "feuerbohne": "Bohne",
  "prinzessbohne": "Bohne",
};

export const INVEKOS_API_BASE = "https://gis.lfrz.gv.at/api/geodata/i009501/ogc/features/v1/collections";
export const INVEKOS_BBOX_DELTA = 0.001;
export const INVEKOS_FETCH_TIMEOUT_MS = 10000;
export const INVEKOS_RESULT_LIMIT = 10;
